### ISSUE TITLE
ApiHandler unknown method or endpoint

### ISSUE THREAD

**Issue by Nixeus2** [jchristn/PuppyProxy#1]
Hello,

I'm trying your proxy in google chrome and edge, on Windows 10, some wepages are ok to load, some don't, i have these traces in the console :

10/02/2019 14:09:27 Warn thr-53 ApiHandler unknown method or endpoint: GET http://farm1.staticflickr.com/44/143981096_60f7e6cb7e_o.jpg

10/02/2019 14:09:27 Warn thr-48 ApiHandler unknown method or endpoint: GET http://www.printableparadise.com/letters/printable-letter-m-silhou

> What does it mean ? Any way to solve it ?

Thanks

**Comment by jchristn** [comment]
Hi @Nixeus2 it could potentially be how you have your proxy configured in Windows 10.  Do you have different values for HTTP vs secure in Internet Options?  Here is my working configuration.  Also you have to run PuppyProxy as administrator.

![image](https://user-images.githubusercontent.com/1421081/66057579-d2692900-e4ed-11e9-8dc1-bba70a40c1a6.png)

**Comment by jchristn** [comment]
Also note that it's a little slow, I need to spend some time updating its dependencies and make it async.

**Comment by jchristn** [comment]
Hi @Nixeus2 sorry both should be pointed to the TCP endpoint.  After revisiting this project it's clear I have to put some time into it to clean it up.  It's in rough shape right now.  Will take me some time to get a more reliable pass in on this, will work on this as I can.

**Comment by Nixeus2** [comment]
Thanks a lot, i will try ! This proxy does support Get and Put too ?

**Comment by jchristn** [comment]
It does, it should support any verb and also CONNECT tunnels.  But again I need to spend some time on it, seems slow/inefficient and has issues with W10 at least.  Thanks for your patience.

**Comment by Nixeus2** [comment]
No problem, take time :)

**Comment by jchristn** [comment]
Hi @Nixeus2 try downloading the latest, commit is here: https://github.com/jchristn/PuppyProxy/commit/fa2089107749ef63bb1ffa47a8bc966655556274

This should work much better.  

You can also test without changing Internet Options to point to the proxy by using ```curl -x http://127.0.0.1:8000 [then your URL]```.

Let me know!

**Comment by jchristn** [comment]
Closing, please let me know if any issues
